server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boulderdb
    username: postgres
    password: ------

  jpa:
    hibernate:
      ddl-auto: update         # erstellt Tabellen automatisch
    show-sql: true             # zeigt SQL-Befehle in der Konsole


