server:
  port: 8080

jwt:
  secret: blabla


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boulderdb
    username: postgres
    password: blabla!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${jwt.secret}

app:
  notifications:
    webhook: "https://discord.com/api/webhooks/1420541593701716112/5xhzG5nzbOQu23iEQTcdiUNl4YtzJLRUaKKP-SSFpmPwtz8sNmL3rerHsD2qBRVVIy0t"
